name: packer Azure

on:
  push:
    branches:
      - main

jobs:
  packer:
      runs-on: windows-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
      
          - name: Setup `packer`
            uses: hashicorp/setup-packer@main
            id: setup
            with:
              version: "latest"
      
          - name: Run `packer init`
            id: init
            run: "packer init ./windows.pkr.hcl"
      
          - name: Run `packer validate`
            id: validate
            run: "packer validate /windows"
            env:
                PKR_VAR_CID: ${{ secrets.PKR_VAR_AZURE_CLIENT_ID }}
                PKR_VAR_CSECRET: ${{ secrets.PKR_VAR_AZURE_CLIENT_SECRET }}
                PKR_VAR_TENANTID: ${{ secrets.PKR_VAR_AZURE_TENANT_ID }}
                PKR_VAR_SUBSCRIPTIONID: ${{ secrets.PKR_VAR_AZURE_SUBSCRIPTION_ID }}
            
          - name: Run `packer build`
            run: "packer build -color=false -on-error=abort /windows"
            env:
                PKR_VAR_CID: ${{ secrets.PKR_VAR_AZURE_CLIENT_ID }}
                PKR_VAR_CSECRET: ${{ secrets.PKR_VAR_AZURE_CLIENT_SECRET }}
                PKR_VAR_TENANTID: ${{ secrets.PKR_VAR_AZURE_TENANT_ID }}
                PKR_VAR_SUBSCRIPTIONID: ${{ secrets.PKR_VAR_AZURE_SUBSCRIPTION_ID }}
