name: packer Azure

on:
  push:
    branches:
      - main

jobs:
  packer:
      runs-on: Windows
      steps:
          - name: Checkout
            uses: actions/checkout@v3
      
          - name: Setup `packer`
            uses: hashicorp/setup-packer@main
            id: setup
            with:
              version: "latest"
      
          - name: Run `packer init`
            id: init
            run: "packer init windows/"
      
          - name: Run `packer validate`
            id: validate
            run: "packer validate windows/"
            env:
                PKR_VAR_CID: ${{ secrets.PKR_VAR_AZURE_CLIENT_ID }}
                PKR_VAR_CSECRET: ${{ secrets.PKR_VAR_AZURE_CLIENT_SECRET }}
                PKR_VAR_TENANTID: ${{ secrets.PKR_VAR_AZURE_TENANT_ID }}
                PKR_VAR_SUBSCRIPTIONID: ${{ secrets.PKR_VAR_AZURE_SUBSCRIPTION_ID }}
            
          - name: Run `packer build`
            run: "packer build -color=false windows/"
            env:
                PKR_VAR_CID: ${{ secrets.PKR_VAR_AZURE_CLIENT_ID }}
                PKR_VAR_CSECRET: ${{ secrets.PKR_VAR_AZURE_CLIENT_SECRET }}
                PKR_VAR_TENANTID: ${{ secrets.PKR_VAR_AZURE_TENANT_ID }}
                PKR_VAR_SUBSCRIPTIONID: ${{ secrets.PKR_VAR_AZURE_SUBSCRIPTION_ID }}
                HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
                HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
                HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"