name: packer Azure

on:
  push:
    branches:
      - main

jobs:
  packer:
      runs-on: windows-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
      
          - name: Setup `packer`
            uses: hashicorp/setup-packer@main
            id: setup
            with:
              version: "latest"
      
          - name: Run `packer init`
            id: init
            run: "packer init ./windows.pkr.hcl"
      
          - name: Run `packer validate`
            id: validate
            run: "packer validate ./windows.pkr.hcl"
            env:
                CID: ${{ secrets.AZURE_CLIENT_ID }}
                CSECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                TENANTID: ${{ secrets.AZURE_TENANT_ID }}
                SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
          - name: Run `packer build`
            run: "packer build -color=false -on-error=abort ./windows.pkr.hcl"
            env:
                CID: ${{ secrets.AZURE_CLIENT_ID }}
                CSECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                TENANTID: ${{ secrets.AZURE_TENANT_ID }}
                SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
